/*
 * This file is generated by jOOQ.
 */
package pay.token.jooq.schema.public_.tables.records;


import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import pay.token.jooq.schema.public_.tables.Card;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CardRecord extends UpdatableRecordImpl<CardRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>PUBLIC.CARD.CARD_REF_ID</code>.
     */
    public void setCardRefId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.CARD.CARD_REF_ID</code>.
     */
    public Long getCardRefId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>PUBLIC.CARD.PAYER_CI</code>.
     */
    public void setPayerCi(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.CARD.PAYER_CI</code>.
     */
    public String getPayerCi() {
        return (String) get(1);
    }

    /**
     * Setter for <code>PUBLIC.CARD.PAYER_NAME</code>.
     */
    public void setPayerName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>PUBLIC.CARD.PAYER_NAME</code>.
     */
    public String getPayerName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>PUBLIC.CARD.CARD_CODE</code>.
     */
    public void setCardCode(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>PUBLIC.CARD.CARD_CODE</code>.
     */
    public String getCardCode() {
        return (String) get(3);
    }

    /**
     * Setter for <code>PUBLIC.CARD.CARD_NUMBER</code>.
     */
    public void setCardNumber(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>PUBLIC.CARD.CARD_NUMBER</code>.
     */
    public String getCardNumber() {
        return (String) get(4);
    }

    /**
     * Setter for <code>PUBLIC.CARD.CARD_VALID_YEAR</code>.
     */
    public void setCardValidYear(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>PUBLIC.CARD.CARD_VALID_YEAR</code>.
     */
    public String getCardValidYear() {
        return (String) get(5);
    }

    /**
     * Setter for <code>PUBLIC.CARD.CARD_VALID_MONTH</code>.
     */
    public void setCardValidMonth(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>PUBLIC.CARD.CARD_VALID_MONTH</code>.
     */
    public String getCardValidMonth() {
        return (String) get(6);
    }

    /**
     * Setter for <code>PUBLIC.CARD.CARD_CVS</code>.
     */
    public void setCardCvs(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>PUBLIC.CARD.CARD_CVS</code>.
     */
    public String getCardCvs() {
        return (String) get(7);
    }

    /**
     * Setter for <code>PUBLIC.CARD.CREATED_TIME</code>.
     */
    public void setCreatedTime(LocalDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>PUBLIC.CARD.CREATED_TIME</code>.
     */
    public LocalDateTime getCreatedTime() {
        return (LocalDateTime) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CardRecord
     */
    public CardRecord() {
        super(Card.CARD);
    }

    /**
     * Create a detached, initialised CardRecord
     */
    public CardRecord(Long cardRefId, String payerCi, String payerName, String cardCode, String cardNumber, String cardValidYear, String cardValidMonth, String cardCvs, LocalDateTime createdTime) {
        super(Card.CARD);

        setCardRefId(cardRefId);
        setPayerCi(payerCi);
        setPayerName(payerName);
        setCardCode(cardCode);
        setCardNumber(cardNumber);
        setCardValidYear(cardValidYear);
        setCardValidMonth(cardValidMonth);
        setCardCvs(cardCvs);
        setCreatedTime(createdTime);
        resetChangedOnNotNull();
    }
}
