/*
 * This file is generated by jOOQ.
 */
package pay.token.jooq.schema.public_.tables.records;


import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import pay.token.jooq.schema.public_.tables.TokenStatus;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TokenStatusRecord extends UpdatableRecordImpl<TokenStatusRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>PUBLIC.TOKEN_STATUS.TOKEN_STATUS_ID</code>.
     */
    public void setTokenStatusId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.TOKEN_STATUS.TOKEN_STATUS_ID</code>.
     */
    public Long getTokenStatusId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>PUBLIC.TOKEN_STATUS.TOKEN_ID</code>.
     */
    public void setTokenId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.TOKEN_STATUS.TOKEN_ID</code>.
     */
    public Long getTokenId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>PUBLIC.TOKEN_STATUS.TOKEN_STATUS_CODE</code>.
     */
    public void setTokenStatusCode(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>PUBLIC.TOKEN_STATUS.TOKEN_STATUS_CODE</code>.
     */
    public String getTokenStatusCode() {
        return (String) get(2);
    }

    /**
     * Setter for <code>PUBLIC.TOKEN_STATUS.CREATED_TIME</code>.
     */
    public void setCreatedTime(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>PUBLIC.TOKEN_STATUS.CREATED_TIME</code>.
     */
    public LocalDateTime getCreatedTime() {
        return (LocalDateTime) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TokenStatusRecord
     */
    public TokenStatusRecord() {
        super(TokenStatus.TOKEN_STATUS);
    }

    /**
     * Create a detached, initialised TokenStatusRecord
     */
    public TokenStatusRecord(Long tokenStatusId, Long tokenId, String tokenStatusCode, LocalDateTime createdTime) {
        super(TokenStatus.TOKEN_STATUS);

        setTokenStatusId(tokenStatusId);
        setTokenId(tokenId);
        setTokenStatusCode(tokenStatusCode);
        setCreatedTime(createdTime);
        resetChangedOnNotNull();
    }
}
