/*
 * This file is generated by jOOQ.
 */
package pay.token.jooq.schema.public_;


import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;

import pay.token.jooq.schema.public_.tables.Author;
import pay.token.jooq.schema.public_.tables.Card;
import pay.token.jooq.schema.public_.tables.Token;
import pay.token.jooq.schema.public_.tables.TokenApproval;
import pay.token.jooq.schema.public_.tables.records.AuthorRecord;
import pay.token.jooq.schema.public_.tables.records.CardRecord;
import pay.token.jooq.schema.public_.tables.records.TokenApprovalRecord;
import pay.token.jooq.schema.public_.tables.records.TokenRecord;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * PUBLIC.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AuthorRecord> CONSTRAINT_7 = Internal.createUniqueKey(Author.AUTHOR, DSL.name("CONSTRAINT_7"), new TableField[] { Author.AUTHOR.ID }, true);
    public static final UniqueKey<CardRecord> CONSTRAINT_1 = Internal.createUniqueKey(Card.CARD, DSL.name("CONSTRAINT_1"), new TableField[] { Card.CARD.CARD_REF_ID }, true);
    public static final UniqueKey<TokenRecord> CONSTRAINT_4 = Internal.createUniqueKey(Token.TOKEN, DSL.name("CONSTRAINT_4"), new TableField[] { Token.TOKEN.TOKEN_ID }, true);
    public static final UniqueKey<TokenApprovalRecord> CONSTRAINT_2 = Internal.createUniqueKey(TokenApproval.TOKEN_APPROVAL, DSL.name("CONSTRAINT_2"), new TableField[] { TokenApproval.TOKEN_APPROVAL.TOKEN_APPROVAL_ID }, true);
}
