/*
 * This file is generated by jOOQ.
 */
package pay.token.jooq.schema.public_;


import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import pay.token.jooq.schema.DefaultCatalog;
import pay.token.jooq.schema.public_.tables.Author;
import pay.token.jooq.schema.public_.tables.Card;
import pay.token.jooq.schema.public_.tables.Token;
import pay.token.jooq.schema.public_.tables.TokenApproval;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>PUBLIC</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>PUBLIC.AUTHOR</code>.
     */
    public final Author AUTHOR = Author.AUTHOR;

    /**
     * The table <code>PUBLIC.CARD</code>.
     */
    public final Card CARD = Card.CARD;

    /**
     * The table <code>PUBLIC.TOKEN</code>.
     */
    public final Token TOKEN = Token.TOKEN;

    /**
     * The table <code>PUBLIC.TOKEN_APPROVAL</code>.
     */
    public final TokenApproval TOKEN_APPROVAL = TokenApproval.TOKEN_APPROVAL;

    /**
     * No further instances allowed
     */
    private Public() {
        super("PUBLIC", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Author.AUTHOR,
            Card.CARD,
            Token.TOKEN,
            TokenApproval.TOKEN_APPROVAL
        );
    }
}
