/*
 * This file is generated by jOOQ.
 */
package pay.token.jooq.schema.public_;


import pay.token.jooq.schema.public_.tables.Author;
import pay.token.jooq.schema.public_.tables.Card;
import pay.token.jooq.schema.public_.tables.Token;
import pay.token.jooq.schema.public_.tables.TokenStatus;


/**
 * Convenience access to all tables in PUBLIC.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>PUBLIC.AUTHOR</code>.
     */
    public static final Author AUTHOR = Author.AUTHOR;

    /**
     * The table <code>PUBLIC.CARD</code>.
     */
    public static final Card CARD = Card.CARD;

    /**
     * The table <code>PUBLIC.TOKEN</code>.
     */
    public static final Token TOKEN = Token.TOKEN;

    /**
     * The table <code>PUBLIC.TOKEN_STATUS</code>.
     */
    public static final TokenStatus TOKEN_STATUS = TokenStatus.TOKEN_STATUS;
}
