/*
 * This file is generated by jOOQ.
 */
package pay.token.jooq.schema.public_;


import pay.token.jooq.schema.public_.tables.Author;


/**
 * Convenience access to all tables in PUBLIC.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>PUBLIC.AUTHOR</code>.
     */
    public static final Author AUTHOR = Author.AUTHOR;
}
